### ISSUE TITLE
How to determine the correct module name from given kernel options

### ISSUE THREAD

**Issue by wildgruber** [graysky2/modprobed-db#11]
Hi graysky,

I'm using modprobed-db to build my (arch) custom kernel, works great!
There's one thing though I fail to understand: how can I determine the correct MODULE name (to put into the $HOME/.config/modprobed.db database) if I only konw a given KERNEL OPTION?

e.g. in order to use docker, docker tells me "CONFIG_NF_NAT_IPV4: missing" (and equally CONFIG_NF_NAT_NEEDED, CONFIG_IP_NF_TARGET_MASQUERADE, CONFIG_NF_NAT_NEEDED); but I can't figure out what module I would have to add to get this turned on in my custom kernel!

If I simply put these names into the database, a warning appears at the beginning of the kernel compilation (with makepkg -s) that "nf_nat_ipv4 config not found!!".

Is it possible to combine the traditional manual "make menuconfig" approach with the automated modprobed-db / localmodconfig mechanism?

Thanks!

**Comment by graysky2** [comment]
I don't think there is a consistent method.  

You should not need to (nor is it recommended to) manually edit modprobed-db's database.  The best method is for you to capture needed modules is to boot into the standard Arch kernel and use docker or whatever.  When you verify it is working fine, run `modprobed-db s` and the module(s) will be automatically detected and added for you.

Now you can build your custom kernel and upon booting into it, should have all the needed functionality.

**Comment by wildgruber** [comment]
Thanks.
That is actually the normal way I use it! (with no manual intervention and via arch standard kernel). 

But in this case (and also for a bunch of multimedia stuff I am bound to use now for the first time, being, like anyone else, forced into doing teaching online! :-/ I found that the standard kernel still runs docker with a more complete feature set (as being shown be their check script) than my custom kernel built with modprobed-db. I can't get to where the standard kernel is, feature-wise.

But never mind, I'll investigate further as soon as it STOPS working!

Thanks again.
