### ISSUE TITLE
Add functionality to "keep modules stored"

### ISSUE THREAD

**Issue by xuanruiqi** [graysky2/modprobed-db#13]
This is a functionality I need. There are some modules which I only occasionally modprobe (e.g., those required for Docker), but would rather have it compiled every time. Otherwise, when I decide I want to use Docker, often I find that I have to rebuild the kernel :-)

I can help with implementing this; it shouldn't be hard, I believe we can just read from a "persistent modules" file and cat it with `modprobed.db`.

I'll see if I can implement this.

**Comment by graysky2** [comment]
I do not understand your request.  This is the reason I wrote modprobed-db in the first place.  Once you have the modules dockers required loaded, you run modprobed-db which adds them to your database.  When you build the kernel, these are built in for you.  What am I missing?

**Comment by xuanruiqi** [comment]
But modules that haven't been modprobe'd in a while will be kicked out of the database, no? It's probably me misunderstanding something.

**Comment by graysky2** [comment]
You are misunderstanding.  Modules are only added, never removed from the database by modprobed-db.  Users can edit the database to remove them if they wish (see man page).

If a module is in your database, but not present on the running kernel (or not hardcoded into the corresponding config you start with), when you go to build, the net effect will be missing that module's functionality in the newly built kernel.

This is not modprobed-db's fault.  `make localmodconfig` [works](https://github.com/torvalds/linux/blob/master/Documentation/admin-guide/README.rst) by creating a new config based on the user provided config + any running modules.  Likely, your docker module(s) were not enabled in the config used to build that running kernel if the corresponding modules were also missing from it.

Also know that new modules get created upstream which you may want but will miss for this same reason, so I recommend the following in the man page:

> As upstream kernel code changes, new modules become available or are removed. It is recommended to boot into a distro default kernel and invoke modprobed-db in store mode to capture any new modules that have become available on new major kernel releases.

I will close this ticket, but feel free to continue the conversation.
