### ISSUE TITLE
[Feature request] List modules that don't get loaded by "recall"

### ISSUE THREAD

**Issue by AdelKS** [graysky2/modprobed-db#15]
Hello!

First of all, thank you for this handy tool! I have a suggestion that would help us make it even more useful: when using `modprobed-db recall` some modules do not get loaded, and it would be nice to know which ones so we enable them from the `.config` file with `make menuconfig` and co, if using `linux-tkg` for example, those additional modules will then be saved in a "fragment" file that can be reused later on.

```shell
151 modules currently loaded per /proc/modules
164 modules are in /home/adel/.config/modprobed.db

Attempting to modprobe the contents of /home/adel/.config/modprobed.db
modprobe: ERROR: could not insert 'amd64_edac_mod': No such device
modprobe: ERROR: could not insert 'fjes': No such device

151 modules are now loaded per /proc/modules
```

**Comment by graysky2** [comment]
Something to consider but pretty low priority given that they fail harmlessly.  PRs welcome.

As an FYI, you do not actually need to load the modules to build a custom kernel, refer to the man page:
>  3.  When building a kernel, simply set the LSMOD variable to the database ($XDG_CONFIG_HOME/modprobed-db) in the make  step:
`make LSMOD=$HOME/.config/modprobed.db localmodconfig`

**Comment by AdelKS** [comment]
Ahaaa I did not know about the `LSMOD trick`, thanks! 

My feature request is not really relevant anymore : what was bothering me was that for example for me, after recall, 151 modules are loaded, but 164 are in the database. And since I wasn't using the `LSMOD` method those modules that haven't been loaded aren't in the newly built custom kernel. I assume the `LSMOD` approach reads the database and toggles the relevant `.config` options.

I think this issue can be safely closed, I will leave the decision to you.

**Comment by graysky2** [comment]
OK, enjoy.
