### ISSUE TITLE
nvme module is not added

### ISSUE THREAD

**Issue by xDShot** [graysky2/modprobed-db#16]
Starting from 5.17 _modprobed-db store_ doesn't add _nvme_ module when it should. I had to manually add the module into `~/.config/modprobed.db` in order to make system bootable from NVMe SSD.

https://github.com/Frogging-Family/linux-tkg is kernel I build with _modprobeddb="true" for Arch Linux.

**Comment by graysky2** [comment]
Are you sure?  Works for me.

```
% grep nvme ~/.config/modprobed.db
nvme
nvme_core
```

**Comment by graysky2** [comment]
Yeah, always a danger of using minimal kernels... in order to get the new modules, you have to boot into a kernel that has them built.

See: https://github.com/graysky2/modprobed-db/blob/master/doc/modprobed-db.8#L82
