### ISSUE TITLE
ck hrtimer patch is awesome in 5.19!!!

### ISSUE THREAD

**Issue by osevan** [graysky2/modprobed-db#17]
Dear graysky2, could you rebase your patchset for latest kernel? 

Thanks and

Best regards

**Comment by graysky2** [comment]
Why are you commenting in this repo?  The patch set has been out for some time: https://github.com/graysky2/linux-patches/commit/9b792e6dc19ee6bd70e7c71f579f4d87ff929c60

**Comment by osevan** [comment]
Because i couldnt opej issue or discussion
Btw can you join our kernel dev channel in Telegram?

We supporting several Scheduler patches and discussing about latency improvment.


https://t.me/+zCzPX4cAFjk1MTYy
