### ISSUE TITLE
Module ac97_bus gets removed by make localmodconfig

### ISSUE THREAD

**Issue by ivanno4317** [graysky2/modprobed-db#18]
The command `make LSMOD=$HOME/.config/modprobed.db localmodconfig` removes `SND_SOC_AC97_CODEC` module.

If the command is ran again it will say:

> module ac97_bus did not have configs CONFIG_AC97_BUS

**Comment by graysky2** [comment]
Is `SND_SOC_AC97_CODEC` in your database?
```
modprobed-db list | grep -i snd_soc
```

**Comment by ivanno4317** [comment]
It is not present in the database. `AC97_BUS` is in the database instead. 
It seems that `SND_SOC_AC97_CODEC` kenel config setting is required to make `AC97_BUS` module load but it gets disabled if i type `make LSMOD=$HOME/.config/modprobed.db localmodconfig`. So there is a problem on how `make localmodconfig` handles the module and the option relative to the module.

**Comment by graysky2** [comment]
My stuff can really only keep book of loaded modules.  If the missing one isn't present in the output of `lsmod`, there isn't anything `modprobed-db` can do about it.

**Comment by ivanno4317** [comment]
My bad! Wrong place to report issue. I'm sorry!

**Comment by graysky2** [comment]
It's fine
