### ISSUE TITLE
Unit file does not exist

### ISSUE THREAD

**Issue by kki0t** [graysky2/modprobed-db#19]
When running trying to enable the user unit via `systemctl --user`, I keep getting `Failed to enable unit: Unit file $HOME/.config/systemd/default.target.wants/modprobed-db.service`.

I noticed that the `default.target.wants` directory doesn't get created.
I can still successfully manually start the user service.

I checked Makepkg logs and both the system service and timer gets installed. No mention of user service there (as expected I think).

**Comment by kraziniSh** [comment]
For context, the Arch Wiki still instructs to enable the user unit. It seems that it isn't necessary anymore, because the timer still runs.
However, enabling the user unit allowed `modprobed-db silentstore` to run on boot and shutdown. Are there remaining ways to do this?

**Comment by graysky2** [comment]
I cannot reproduce.
```
% tree ~/.config/systemd     
[4.0K]  /home/facade/.config/systemd
└── [4.0K]  user
    ├── [ 119]  cleanup.service
    ├── [4.0K]  multi-user.target.wants
    │   └── [  50]  cleanup.service -> /home/squishy/.config/systemd/user/cleanup.service
```

So no default target.
```
% systemctl --user enable modprobed-db 
Created symlink /home/squishy/.config/systemd/user/default.target.wants/modprobed-db.service → /usr/lib/systemd/user/modprobed-db.service.
```
That created it just fine.

**Comment by kki0t** [comment]
Solved.

Kept happening because I manually created systemd user unit directories for a package (`sunshine`<sup>AUR</sup>) that wouldn't do so.
Deleted `~/.config/multi-user.target.wants/` and `~/.config/user/`, then re-ran the systemctl enable command.
Systemd recreated the directories, now everything just works.

Did I skip a warning on their man page(s)?

**Comment by pyrotiger** [comment]
the Archi wiki actually states to enable service as a user unit so using `systemctl --user enable modprobe-db` was correct

**Comment by xlacroixx** [comment]
> the Archi wiki actually states to enable service as a user unit so using `systemctl --user enable modprobe-db` was correct

Of course, that was not the problem. The problem was creating unit directories in `~/.config/systemd` manually instead of letting systemd create it by itself (e.g. by enabling a unit for the first time).

So morale is that systemd sucks.
