### ISSUE TITLE
Any chance of having a /usr/local install option?

### ISSUE THREAD

**Issue by vaskark** [graysky2/modprobed-db#25]
I've tried changing some of the Makefile options but it seems the modprobed-db.skel file is still causing some issues. It would be nice if it fully worked in /usr/local.

Thanks.

**Comment by graysky2** [comment]
The issue is that line 11 in the script is a hard-coded path... you can build the latest version with:
```
make PREFIX=/usr/local
make DESTDIR/usr/local install
```

That should work.  Please try it and let me know.

**Comment by vaskark** [comment]
In Makefile:

`INITDIR_SYSTEMD = /usr/lib/systemd/user
`
should be 

`INITDIR_SYSTEMD=$(PREIFX)/lib/systemd/user`

**Comment by graysky2** [comment]
You're right, thanks.  Please try latest commit.

**Comment by vaskark** [comment]
Using `make PREFIX=/usr/local` and `make DESTDIR=/usr/local` still puts the files in` /usr/local/usr/ ...`

I've found that if I edit PREFIX in the Makefile to `/usr/local`, then `make` and` sudo make install` it installs perfectly.  Uninstall is perfect, too.

**Comment by graysky2** [comment]
I see that as well... I do not know how to pass the custom value of PREFIX to the install step

**Comment by vaskark** [comment]
Lol me neither. 

I might just use a custom branch for the Makefile for the time being.

Btw, thanks for all your hard work.

**Comment by graysky2** [comment]
OK, enjoy
