### ISSUE TITLE
SUDO_USER is not defined

### ISSUE THREAD

**Issue by boogerlad** [graysky2/modprobed-db#3]
If I'm running as root, `USER` gets assigned to `SUDO_USER` which is not defined. Then, I get `Error: Cannot figure out who ran this script. Bailing out` But `root` ran the script! What's the problem? Why can't we just always use the value of `whoami`?

**Comment by graysky2** [comment]
Which terminal are you using?

**Comment by boogerlad** [comment]
I'm using terminator, but I'm getting this error with systemctl's timer on arch wiki.

**Comment by graysky2** [comment]
I haven't tried using it with a systemctl timer running as root.  I designed it to run as a normal user (ie cron).  Can you set your timer to run as your user and see if that works?

**Comment by boogerlad** [comment]
uhoh I'm a bad person my user is root!

**Comment by graysky2** [comment]
Please try version 2.27 with your systemd timer running as root.  I am able to run as root with this code.

**Comment by boogerlad** [comment]
Sorry I have been gone so long but I just tested this and it works perfectly now!!! Thank you!!

**Comment by boogerlad** [comment]
Hmm, I tried updating linux-ck with modprobe-db enabled in the pkgbuild and I got the "cannot determine your username so exiting" Inspecting the script, I see this

```
elif [[ "$SUDO_USER" = "root" ]]; then
  mesg="Cannot determine your username so exiting."
  echo -e "==> ERROR: ${mesg}" && exit 1
```
Is this an intentional thing to prevent running it as root?

**Comment by graysky2** [comment]
So you set the service to your user, not root?  The database should be in your homedir then.  Is it?

**Comment by boogerlad** [comment]
My user is root. The service is set to root. I am updating the linux-ck package with yaourt as root as well. I'm not sure where the database is located since I am not with the computer with Arch atm.

**Comment by graysky2** [comment]
Have to revisit this.  I never intended users to run it as root but the database should be in `/root/.config/modprobed.*` if you're running it as root.

**Comment by graysky2** [comment]
I cannot reproduce this.  Even if I login as root I am able to store and recall as root without any errors.  Can you confirm?

**Comment by boogerlad** [comment]
I can't reproduce either. Not enough time and no desktop. I will reopen when the time comes.
