### ISSUE TITLE
systemd timer

### ISSUE THREAD

**Issue by Narrat** [graysky2/modprobed-db#5]
Got a few notes/questions.

1) https://github.com/graysky2/modprobed-db/blob/master/init/modprobed-db%40.service#L3
It contains the info about the manpage twice. So on checking the status there will be
>Documentation: modprobed-db(8)
Documentation: modprobed-db(8)
Documentation: https://wiki.archlinux.org/index.php/Modprobed-db

2) Couldn't this be added as a systemd --user unit files (placed under /usr/lib/systemd/user/ )? As far as I can tell this would simplify both unit files a bit.

3) Is oneshot the right thing to do? As far as I can tell (and what systemd list-timers tells me) the unit is just run once.

4) Regarding the doc. The Arch-Wiki states it's just necessary to enable and start the timer
https://wiki.archlinux.org/index.php/Systemd/Timers#Service_unit
whereas here it is adviced to enable the service@user

5) Shouldn't be an OnBootSec=  added? Directly after boot it's not very likely to get new modules, and additionally 30min shouldn't hurt there.

Hope you can enlighten me. I'm relatively new at the topic unit files and it's likely I missed something

Best regards

**Comment by graysky2** [comment]
Thank you for the thoughtful feedback.

1) Typo, I meant to have both the - and _ but makes sense to just keep it as - at this point.  Fixed in https://github.com/graysky2/modprobed-db/commit/170387935d0f2d995d3df784a09560ae5cf8c2d7
2) I never go the user mode of systemd to work and haven't tried since.
3) If not oneshot, than what type?
4) If true, that's new to me.  I have always just started the services.
5) It's setup now to run once per hour and on reboot/shutdown.  I don't see the value of adding a boot delay.

**Comment by Narrat** [comment]
1) Ah, didn't thought about a possible typo. Since the _ stuff should vanish at some point?

2) I tried it recently without additional setup (afair this was not so easy back then). Imo it should working now easily, as a user session is started after someone logs in.
3) I suppose it would be the default, "simple"

4) To quote the Arch-Wiki
>For each .timer file, a matching .service file exists (e.g. foo.timer and foo.service). The .timer file activates and controls the .service file. The .service does not require an [Install] section as it is the timer units that are enabled. If necessary, it is possible to control a differently-named unit using the Unit= option in the timer's [Timer] section.

5) I thought mostly about the case if this is running directly after startup. But not sure atm if that's the case. More a personal taste thing. So.. fine as it now

**Comment by Narrat** [comment]
Did upload my local setup to visualize my points and problems (somewhat)
https://github.com/Narrat/modprobed-db/tree/usersystemd
With user systemd unit files, just enabled and started .timer, oneshot and this is the result (oh and my local files still had the boot delay of 30m)

(usystemctl is an alias for systemctl --user)
>$ usystemctl status modprobed-db.timer
● modprobed-db.timer - Timer for modprobed-db - 1Hour
   Loaded: loaded (/home/omnius/.config/systemd/user/modprobed-db.timer; enabled; vendor preset: enabled)
   Active: active (waiting) since Di 2015-06-23 17:47:01 CEST; 22min ago

>Jun 23 17:47:01 Persephone systemd[649]: Started Timer for modprobed-db - 1Hour.
Jun 23 17:47:01 Persephone systemd[649]: Starting Timer for modprobed-db - 1Hour.
$ usystemctl list-timers              
NEXT                         LEFT      LAST PASSED UNIT               ACTIVATES
Di 2015-06-23 18:16:30 CEST  6min left n/a  n/a    modprobed-db.timer modprobed-db.service

after:

>$ usystemctl status modprobed-db.timer
● modprobed-db.timer - Timer for modprobed-db - 1Hour
   Loaded: loaded (/home/omnius/.config/systemd/user/modprobed-db.timer; enabled; vendor preset: enabled)
   Active: active (running) since Di 2015-06-23 17:47:01 CEST; 31min ago

>Jun 23 17:47:01 Persephone systemd[649]: Started Timer for modprobed-db - 1Hour.
Jun 23 17:47:01 Persephone systemd[649]: Starting Timer for modprobed-db - 1Hour.
$ usystemctl list-timers              
NEXT                         LEFT         LAST                         PASSED       UNIT               ACTIVATES
Di 2015-06-23 18:16:30 CEST  1min 44s ago Di 2015-06-23 18:16:43 CEST  1min 31s ago modprobed-db.timer modprobed-db.serv

Normally I would expect so see at NEXT 19:16:xx

**Comment by Narrat** [comment]
Forgot to report back. 
Changing it from "oneshot" to "simple" produces this output
>NEXT                         LEFT          LAST                         PASSED    UNIT               ACTIVATES
Mi 2015-07-29 21:15:50 CEST  1min 30s left Mi 2015-07-29 20:15:50 CEST  58min ago modprobed-db.timer modprobed-db.service

So it's working

(And forgot to add in the last post, with the service files provided with this repo I get the "run once and nothing else" result)

**Comment by graysky2** [comment]
The package provided service and timer work for me.  Can you please try again and report back.

**Comment by Narrat** [comment]
Just starting the timer (the normal way)
> $ sudo systemctl start modprobed-db@omnius.timer
 $ systemctl list-timers
NEXT                         LEFT           LAST                         PASSED     UNIT                         ACTIVATES
n/a                          n/a            n/a                          n/a        modprobed-db@omnius.timer    modprobed-db@omnius.service
(...)

Starting service, then timer
>$ sudo systemctl start modprobed-db@omnius.service
 $ sudo systemctl start modprobed-db@omnius.timer
 $ systemctl list-timers
NEXT                         LEFT           LAST                         PASSED     UNIT                         ACTIVATES
Sa 2015-08-22 14:56:09 CEST  59min left     n/a                          n/a        modprobed-db@omnius.timer    modprobed-db@omnius.service
(...)

(1h later)
> $ systemctl list-timers
NEXT                         LEFT          LAST                         PASSED      UNIT                         ACTIVATES
Sa 2015-08-22 14:56:09 CEST  10min ago     Sa 2015-08-22 14:56:26 CEST  10min ago   modprobed-db@omnius.timer    modprobed-db@omnius.service
(...)

**Comment by graysky2** [comment]
So you're suggesting the change from 'oneshot' to 'simple' and in doing so, everything works for you as expected?

**Comment by Narrat** [comment]
Yes, after changing it to simple (and 5min for demo)
> $ systemctl list-timers
NEXT                         LEFT          LAST                         PASSED       UNIT                         ACTIVATES
Sa 2015-08-22 16:47:16 CEST  4min 7s left  Sa 2015-08-22 16:42:16 CEST  52s ago      modprobed-db@omnius.timer    modprobed-db@omnius.service
(...)

Although I additionally favor the move from system unit files to user unit files, as I don't see a reason to use system unit files. The "complicating" stuff like getting the USER won't be topic, and instead of starting and enabling both unit files it would suffice to start and enable the timer

**Comment by Narrat** [comment]
With latest release (2.33) this should be resolved. User service files working fine.

I found also an explanation for point 4 in the first post. (Me wondering about enabling both unit files)
Didn't read throroughly enough the man-page for "OnUnitActiveSec".
Combining it with "OnBootSec" which activates the service after time x after boot and then "OnUnitAcitveSec" handles it from that point. So just the timer needs to be enabled.

I don't propose a change, I just want to document it, so should someone read this issue, he would find comments an all points.
